### ISSUE TITLE
Running Botsing 1.0.1 programatically

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/botsing#19]
#### Characteristics

- **Tool/Service/Component**: [Botsing, 1.0.1]
- **Execution Environment**: Linux
- **Reporter**: [Ricardo Tejada,<ricardo.tejada.external@atos.net>]

#### Description

If I run Botsing in the Terminal : java -jar ....-with-dependencies.jar (command line)

where command line is : 

-Dpopulation=100 -Dsearch_budget=1800 -Dmax_recursion=30 -Dtest_dir=/home/ricardo/eclipse-workspace/ExceptionsForBotsing/tests -crash_log /home/ricardo/eclipse-workspace/ExceptionsForBotsing/logs/null_pointer_example.log -target_frame 2 -projectCP /home/ricardo/eclipse-workspace/ExceptionsForBotsing/target

it works fine, but if I try to run it in a java application using 

Botsing.main(command line);

it shows this Error message :

wrong arguments. Available options are:
[ Options: [ short {f=[ option: f flatten  :: use this option to flatten the stack trace :: class java.lang.Boolean ], l=[ option: l crash_log  [ARG] :: path to the input stack trace :: class java.lang.String ], o=[ option: o output_log  [ARG] :: path to the output stack trace after processing :: class java.lang.String ], e=[ option: e error_message  :: use this option to remove the error message :: class java.lang.String ], a=[ option: a annotations  :: UNSUPPORTED: use this option to remove the frames related to annotations :: class java.lang.String ]} ] [ long {flatten=[ option: f flatten  :: use this option to flatten the stack trace :: class java.lang.Boolean ], crash_log=[ option: l crash_log  [ARG] :: path to the input stack trace :: class java.lang.String ], output_log=[ option: o output_log  [ARG] :: path to the output stack trace after processing :: class java.lang.String ], error_message=[ option: e error_message  :: use this option to remove the error message :: class java.lang.String ], annotations=[ option: a annotations  :: UNSUPPORTED: use this option to remove the frames related to annotations :: class java.lang.String ]} ]

How should I run it ?
Thank you.

**Comment by jesus-gorronogoitia** [comment]
Hi @RicardoTej , I've discussed this issue with @pderakhshanfar 
Please, add debug logging in the line you invoke `Botsing.main(command line);` to check that arguments passed to Botsing are correct.
You can also import Botsing project in order to debug Botsing main and parseParameters methods, and to check what is going on behind the scenes.
Once you confirm that CLI parameters are passed correctly to Botsing, you may want to check that using the last released [botsing-reproduction.jar file](https://github.com/STAMP-project/botsing/releases/download/botsing-1.0.0/botsing-reproduction-1.0.0.jar), you still have the problem. In order words, that it is not caused because of using a wrong Botsing library/code.
Additionally, Pouria has pointed me to a [BotsingTest.java](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/test/java/eu/stamp/botsing/BotsingTest.java) you can inspect to understand how to invoke Botsing.

**Comment by RicardoTej** [comment]
BotsingTest.java contains the answer to my question
Thank you.

**Comment by RicardoTej** [comment]
BotsingTest.java contains the answer to my question
Thank you.
